# 默认只打印 WARN（警告）和 ERROR（错误），把恶心的 INFO 全部屏蔽
log4j.rootLogger=WARN, stdout

# 控制台输出设置
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p [%t] %c{1}: %m%n

# 针对 Zookeeper 和 HBase 的包，强制调高日志级别到 WARN
log4j.logger.org.apache.zookeeper=WARN
log4j.logger.org.apache.hadoop.hbase=WARN